"""add notification fields

Revision ID: 27389e0342a0
Revises: 36bc3d23dd9b
Create Date: 2026-08-20 09:21:56.807628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27389e0342a0'
down_revision: Union[str, None] = '36bc3d23dd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default keeps ADD COLUMN working on non-empty SQLite tables and
    # gives sane defaults on Postgres.
    op.add_column('series', sa.Column('notify_email', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('series', sa.Column('notify_discord', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('series', sa.Column('notify_telegram', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('discord_webhook_url_encrypted', sa.String(length=2000), nullable=False, server_default=sa.text("''")))
    op.add_column('users', sa.Column('telegram_bot_token_encrypted', sa.String(length=1000), nullable=False, server_default=sa.text("''")))
    op.add_column('users', sa.Column('telegram_chat_id_encrypted', sa.String(length=255), nullable=False, server_default=sa.text("''")))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_chat_id_encrypted')
    op.drop_column('users', 'telegram_bot_token_encrypted')
    op.drop_column('users', 'discord_webhook_url_encrypted')
    op.drop_column('series', 'notify_telegram')
    op.drop_column('series', 'notify_discord')
    op.drop_column('series', 'notify_email')
    # ### end Alembic commands ###
