"""add notification email

Revision ID: 2a26d80ee46c
Revises: 27389e0342a0
Create Date: 2026-08-20 10:06:20.328582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a26d80ee46c'
down_revision: Union[str, None] = '27389e0342a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('notification_email', sa.String(length=255), nullable=False, server_default=sa.text("''")))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_email')
    # ### end Alembic commands ###
